name: aoc-to-markdown Release

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 24.x
        uses: actions/setup-node@v4
        with:
          node-version: 24.x
      - run: npm ci
      - run: npm run lint
      - run: npm run build
      - name: Create Release
        run: |
          mv ./web-ext-artifacts/aoc-to-markdown-chrome.zip ./web-ext-artifacts/aoc-to-markdown-chrome-${{ github.ref_name }}.zip
          mv ./web-ext-artifacts/aoc-to-markdown-firefox.zip ./web-ext-artifacts/aoc-to-markdown-firefox-${{ github.ref_name }}.zip
          gh release create ${{ github.ref_name }} \
            --title "Advent of Code to Markdown ${{ github.ref_name }}" \
            ./web-ext-artifacts/aoc-to-markdown-chrome-${{ github.ref_name }}.zip \
            ./web-ext-artifacts/aoc-to-markdown-firefox-${{ github.ref_name }}.zip
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
